version: 2
updates:
- package-ecosystem: bundler
  allowed_updates:
  - match:
    dependency_type: "development"
    dependency-type: all
  - match:
    dependency_type: "production"
    update_type: "security"
  directory: '/'
  open-pull-requests-limit: 10
  schedule:
    interval: daily
  version_requirement_updates: "increase_versions"
  versioning-strategy: lockfile-only
